name: PR AI Assistant (suggest)

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-ai-assistant-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-and-comment:
    runs-on: ubuntu-latest
    # Minimal permissions: allow writing comments via issues API using the default GITHUB_TOKEN
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run lint (non-blocking)
        run: npm run lint || true
      - name: Run tests (collect results)
        run: npm test -- --runInBand --json --outputFile=./test-results.json || true
      - name: Compose suggestion and comment (read-only)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: node .github/ai/compose-suggestion.cjs
